# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reputation',
            field=models.IntegerField(default=120),
        ),
    ]
