# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact_email',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='contact_number',
            field=models.IntegerField(default=250, null=True),
        ),
    ]
