# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0002_auto_20180714_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='ad_pictures'),
        ),
    ]
