# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-14 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0003_auto_20180714_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact_number',
            field=models.IntegerField(blank=True, default=250, null=True),
        ),
    ]
